# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NmNmNWQ1N2FkZDlkZjQzODA5MTFjNzVjNmE0NjNiNjdjYWQ4OTg2OTY0YTQzNmU1NWI5NzE5OGNhODQ2MTI4ZDEwNWZkOWU4NzIwN2VkZGUzYzYyYmUwNTBlMGViOGMzN2Q3ZjZkNWY5YmI0YTc2MzRmOWY0MGQzZjMyMGNkZGY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
